language: cpp
compiler:
- g++
before_script:
- mkdir build
- cd build
- cmake ..
script: make
addons:
  ssh_known_hosts:
  - 30.30.210.36
before_install:
- openssl aes-256-cbc -K $encrypted_dafae5a610c8_key -iv $encrypted_dafae5a610c8_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
after_success:
- ssh  -p 9999 xiangkun.jxk@30.30.210.36  -o StrictHostKeyChecking=no 'cd ~/git/ci-test &&
  git pull'
