language: cpp
compiler:
- g++
before_script:
- mkdir build
- cd build
- cmake ..

script: make

dd:
- openssl aes-256-cbc -K $encrypted_dafae5a610c8_key -iv $encrypted_dafae5a610c8_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d

after_success:
- ssh xiangkun.jxk@100.88.106.7  -o StrictHostKeyChecking=no 'cd ~/git/ci-test && git pull'   #使用ssh连接服务器

